/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsHowto = {
    // 모든 튜토리얼 문서에 대해 자동으로 사이드바 생성
    howtoSidebar: [{ type: 'autogenerated', dirName: '.' }],
    // 혹은 수동으로 카테고리/문서 명시:
    // howtoSidebar: [
    //   'intro', 
    //   {
    //     type: 'category', label: 'Category 1', items: ['category1/doc1', 'category1/doc2']
    //   },
    // ],
  };
  module.exports = sidebarsHowto;